services:
  laravel:
    build:
      context: .
      target: runtime_php
    container_name: destino_laravel
    env_file: .env.docker
    ports:
      - 8000:8000
    volumes:
      - ./public:/app/public

  node:
    build:
      context: .
      target: runtime_node
    container_name: destino_node
    depends_on:
      - laravel
