/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "contato": [],
    "buscar": [],
    "pacote.detalhes": [
        {
            "name": "nome",
            "required": true
        }
    ],
    "cadastro": [],
    "entrar": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "logout": [],
    "checkout": [
        {
            "name": "ofertaId",
            "required": true
        }
    ],
    "checkout.process": [
        {
            "name": "ofertaId",
            "required": true
        }
    ],
    "user.profile.edit": [],
    "user.profile.update": [],
    "user.profile.password": [],
    "usuario.viagem.detalhes": [
        {
            "name": "id",
            "required": true
        }
    ],
    "usuario.viagem.avaliar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "usuario.viagem.salvar_avaliacao": [
        {
            "name": "id",
            "required": true
        }
    ],
    "usuario.viagem.listar": [
        {
            "name": "usuario",
            "required": false
        }
    ],
    "administracao.dashboard": [],
    "administracao.dashboard.estatisticas": [],
    "administracao.hotel.index": [],
    "administracao.hotel.create": [],
    "administracao.hotel.store": [],
    "administracao.hotel.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.hotel.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.hotel.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.transporte.index": [],
    "administracao.transporte.create": [],
    "administracao.transporte.store": [],
    "administracao.transporte.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.transporte.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.transporte.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote-foto.index": [],
    "administracao.pacote-foto.create": [],
    "administracao.pacote-foto.store": [],
    "administracao.pacote-foto.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote-foto.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote-foto.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote.index": [],
    "administracao.pacote.create": [],
    "administracao.pacote.store": [],
    "administracao.pacote.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.pacote.compras": [
        {
            "name": "pacote",
            "required": true
        }
    ],
    "administracao.oferta.index": [],
    "administracao.oferta.create": [],
    "administracao.oferta.store": [],
    "administracao.oferta.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.oferta.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.oferta.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.usuario.index": [],
    "administracao.usuario.create": [],
    "administracao.usuario.store": [],
    "administracao.usuario.edit": [
        {
            "name": "nome",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.usuario.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.usuario.update-status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "administracao.usuario.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
