/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "cadastro": [],
    "entrar": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "logout": [],
    "buscar": [],
    "contato": [],
    "administracao.dashboard": [],
    "administracao.dashboard.estatisticas": [],
    "administracao.hotel.listar": [],
    "administracao.hotel.edit": [
        {
            "name": "hotel",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.hotel.store": [],
    "administracao.hotel.update": [
        {
            "name": "hotel",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.hotel.destroy": [
        {
            "name": "hotel",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.hotel.registrar": [],
    "administracao.pacote.listar": [],
    "administracao.pacote.edit": [
        {
            "name": "pacote",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacote.compras": [
        {
            "name": "pacote",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacote.store": [],
    "administracao.pacote.update": [
        {
            "name": "pacote",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacote.destroy": [
        {
            "name": "pacote",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacote.registrar": [],
    "administracao.pacotedefoto.listar": [],
    "administracao.pacotedefoto.edit": [
        {
            "name": "pacotedefoto",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacotedefoto.store": [],
    "administracao.pacotedefoto.update": [
        {
            "name": "pacotedefoto",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacotedefoto.destroy": [
        {
            "name": "pacotedefoto",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.pacotedefoto.registrar": [],
    "administracao.usuario.registrar": [],
    "administracao.usuario.store": [],
    "administracao.usuario.listar": [],
    "administracao.usuario.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.compras": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.resend-invitation": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.aprovar": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.toggle-block": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.update-access": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.usuario.perfil-update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.oferta.listar": [],
    "administracao.oferta.edit": [
        {
            "name": "oferta",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.offer.store": [],
    "administracao.offer.update": [
        {
            "name": "oferta",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.offer.destroy": [
        {
            "name": "oferta",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.oferta.registrar": [],
    "administracao.transporte.listar": [],
    "administracao.transporte.edit": [
        {
            "name": "transporte",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.transport.store": [],
    "administracao.transport.update": [
        {
            "name": "transporte",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.transport.destroy": [
        {
            "name": "transporte",
            "required": true,
            "binding": "id"
        }
    ],
    "administracao.transporte.registrar": [],
    "checkout.index": [],
    "checkout.processar": [],
    "checkout.confirmacao": [
        {
            "name": "compraId",
            "required": true
        }
    ],
    "pacote.detalhes": [
        {
            "name": "nome",
            "required": true
        }
    ],
    "usuario.viagem.listar": [
        {
            "name": "user",
            "required": true,
            "binding": "slug"
        }
    ],
    "usuario.viagem.detalhes": [
        {
            "name": "user",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "compra",
            "required": true,
            "binding": "id"
        }
    ],
    "usuario.perfil.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "slug"
        }
    ],
    "usuario.perfil.update": [
        {
            "name": "user",
            "required": true,
            "binding": "slug"
        }
    ],
    "usuario.perfil.password": [
        {
            "name": "user",
            "required": true,
            "binding": "slug"
        }
    ],
    "usuario.perfil.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "slug"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
