--
-- PostgreSQL Database Schema — Projeto Destino
-- Gerado a partir do dump original, consolidado para legibilidade.
-- Cada CREATE TABLE contém todas as suas constraints (PK, FK, UNIQUE) inline.
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;


-- ============================================================================
-- TABELAS INDEPENDENTES (sem foreign keys para outras tabelas do domínio)
-- ============================================================================


-- ----------------------------------------------------------------------------
-- migrations
-- ----------------------------------------------------------------------------
CREATE TABLE public.migrations (
    id              integer         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration       varchar(255)    NOT NULL,
    batch           integer         NOT NULL
);


-- ----------------------------------------------------------------------------
-- failed_jobs
-- ----------------------------------------------------------------------------
CREATE TABLE public.failed_jobs (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            varchar(255)    NOT NULL  UNIQUE,
    connection      text            NOT NULL,
    queue           text            NOT NULL,
    payload         text            NOT NULL,
    exception       text            NOT NULL,
    failed_at       timestamp(0)    NOT NULL  DEFAULT CURRENT_TIMESTAMP
);


-- ----------------------------------------------------------------------------
-- jobs
-- ----------------------------------------------------------------------------
CREATE TABLE public.jobs (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue           varchar(255)    NOT NULL,
    payload         text            NOT NULL,
    attempts        smallint        NOT NULL,
    reserved_at     integer,
    available_at    integer         NOT NULL,
    created_at      integer         NOT NULL
);

CREATE INDEX jobs_queue_reserved_at_available_at_index
    ON public.jobs USING btree (queue, reserved_at, available_at);


-- ----------------------------------------------------------------------------
-- job_batches
-- ----------------------------------------------------------------------------
CREATE TABLE public.job_batches (
    id              varchar(255)    PRIMARY KEY,
    name            varchar(255)    NOT NULL,
    total_jobs      integer         NOT NULL,
    pending_jobs    integer         NOT NULL,
    failed_jobs     integer         NOT NULL,
    failed_job_ids  text            NOT NULL,
    options         text,
    cancelled_at    integer,
    created_at      integer         NOT NULL,
    finished_at     integer
);


-- ----------------------------------------------------------------------------
-- cache
-- ----------------------------------------------------------------------------
CREATE TABLE public.cache (
    key             varchar(255)    PRIMARY KEY,
    value           text            NOT NULL,
    expiration      integer         NOT NULL
);

CREATE INDEX cache_expiration_index
    ON public.cache USING btree (expiration);


-- ----------------------------------------------------------------------------
-- cache_locks
-- ----------------------------------------------------------------------------
CREATE TABLE public.cache_locks (
    key             varchar(255)    PRIMARY KEY,
    owner           varchar(255)    NOT NULL,
    expiration      integer         NOT NULL
);

CREATE INDEX cache_locks_expiration_index
    ON public.cache_locks USING btree (expiration);


-- ----------------------------------------------------------------------------
-- password_reset_tokens
-- ----------------------------------------------------------------------------
CREATE TABLE public.password_reset_tokens (
    email           varchar(255)    PRIMARY KEY,
    token           varchar(255)    NOT NULL,
    created_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- tags
-- ----------------------------------------------------------------------------
CREATE TABLE public.tags (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(255)    NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- transportes
-- ----------------------------------------------------------------------------
CREATE TABLE public.transportes (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa         varchar(100)    NOT NULL,
    meio            varchar(255)    NOT NULL,
    preco           integer         NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- regiaos (regiões)
-- ----------------------------------------------------------------------------
CREATE TABLE public.regiaos (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla           varchar(2)      NOT NULL,
    nome            varchar(12)     NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- pacote_fotos
-- ----------------------------------------------------------------------------
CREATE TABLE public.pacote_fotos (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(255)    NOT NULL,
    storage_type    varchar(255)    NOT NULL  DEFAULT 'local',
    foto_capa       text            NOT NULL,
    is_url          boolean         NOT NULL  DEFAULT false,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- roles
-- ----------------------------------------------------------------------------
CREATE TABLE public.roles (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255)    NOT NULL  UNIQUE,
    description     varchar(255),
    is_staff        boolean         NOT NULL  DEFAULT false,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- permissions
-- ----------------------------------------------------------------------------
CREATE TABLE public.permissions (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            varchar(255)    NOT NULL  UNIQUE,
    description     varchar(255),
    is_staff        boolean         NOT NULL  DEFAULT false,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ============================================================================
-- TABELAS COM DEPENDÊNCIAS (ordem respeitando as foreign keys)
-- ============================================================================


-- ----------------------------------------------------------------------------
-- activity_log
-- ----------------------------------------------------------------------------
CREATE TABLE public.activity_log (
    id                  bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_name            varchar(255),
    description         text            NOT NULL,
    subject_type        varchar(255),
    subject_id          varchar(255),
    event               varchar(255),
    causer_type         varchar(255),
    causer_id           varchar(255),
    attribute_changes   json,
    properties          json,
    created_at          timestamp(0),
    updated_at          timestamp(0)
);

CREATE INDEX activity_log_log_name_index ON public.activity_log USING btree (log_name);
CREATE INDEX causer                      ON public.activity_log USING btree (causer_type, causer_id);
CREATE INDEX subject                     ON public.activity_log USING btree (subject_type, subject_id);


-- ----------------------------------------------------------------------------
-- estados  →  FK: regiaos
-- ----------------------------------------------------------------------------
CREATE TABLE public.estados (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla           varchar(2)      NOT NULL,
    nome            varchar(100)    NOT NULL,
    regiao_id       bigint,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT estados_regiao_id_foreign
        FOREIGN KEY (regiao_id) REFERENCES public.regiaos (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- cidades  →  FK: estados
-- ----------------------------------------------------------------------------
CREATE TABLE public.cidades (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(40)     NOT NULL,
    estado_id       bigint          NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT cidades_estado_id_foreign
        FOREIGN KEY (estado_id) REFERENCES public.estados (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- hotels  →  FK: cidades
-- ----------------------------------------------------------------------------
CREATE TABLE public.hotels (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(50)     NOT NULL,
    endereco        varchar(100)    NOT NULL,
    diaria          integer         NOT NULL,
    cidade_id       bigint          NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT hotels_cidade_id_foreign
        FOREIGN KEY (cidade_id) REFERENCES public.cidades (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- fotos  →  FK: pacote_fotos
-- ----------------------------------------------------------------------------
CREATE TABLE public.fotos (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(100)    NOT NULL,
    url             varchar(255)    NOT NULL,
    pacote_foto_id  bigint,
    created_at      timestamp(0),
    updated_at      timestamp(0)
);


-- ----------------------------------------------------------------------------
-- pacote_foto_items  →  FK: pacote_fotos
-- ----------------------------------------------------------------------------
CREATE TABLE public.pacote_foto_items (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pacote_foto_id  bigint          NOT NULL,
    caminho         varchar(255)    NOT NULL,
    is_url          boolean         NOT NULL  DEFAULT false,
    ordem           integer         NOT NULL  DEFAULT 0,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT pacote_foto_items_pacote_foto_id_foreign
        FOREIGN KEY (pacote_foto_id) REFERENCES public.pacote_fotos (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- users  →  FK: roles
-- ----------------------------------------------------------------------------
CREATE TABLE public.users (
    id                  uuid            PRIMARY KEY,
    nome                varchar(20)     NOT NULL,
    sobre_nome          varchar(20)     NOT NULL,
    cpf                 text            NOT NULL  UNIQUE,
    email               varchar(50)     NOT NULL  UNIQUE,
    telefone            varchar(11)     NOT NULL,
    password            varchar(255)    NOT NULL,
    is_valid            boolean         NOT NULL  DEFAULT false,
    slug                varchar(255)    NOT NULL  UNIQUE,
    email_verified_at   timestamp(0),
    remember_token      varchar(100),
    role_id             bigint,
    created_at          timestamp(0),
    updated_at          timestamp(0),

    CONSTRAINT users_role_id_foreign
        FOREIGN KEY (role_id) REFERENCES public.roles (id) ON DELETE SET NULL
);


-- ----------------------------------------------------------------------------
-- sessions  →  FK implícita: users (sem constraint formal)
-- ----------------------------------------------------------------------------
CREATE TABLE public.sessions (
    id              varchar(255)    PRIMARY KEY,
    user_id         uuid,
    ip_address      varchar(45),
    user_agent      text,
    payload         text            NOT NULL,
    last_activity   integer         NOT NULL
);

CREATE INDEX sessions_user_id_index        ON public.sessions USING btree (user_id);
CREATE INDEX sessions_last_activity_index  ON public.sessions USING btree (last_activity);


-- ----------------------------------------------------------------------------
-- pacotes  →  FK: users, pacote_fotos
-- ----------------------------------------------------------------------------
CREATE TABLE public.pacotes (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            varchar(100)    NOT NULL,
    descricao       text            NOT NULL,
    funcionario_id  uuid            NOT NULL,
    pacote_foto_id  bigint,
    tag_ids         json,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT pacotes_funcionario_id_foreign
        FOREIGN KEY (funcionario_id) REFERENCES public.users (id) ON DELETE CASCADE,

    CONSTRAINT pacotes_pacote_foto_id_foreign
        FOREIGN KEY (pacote_foto_id) REFERENCES public.pacote_fotos (id) ON DELETE SET NULL
);


-- ----------------------------------------------------------------------------
-- ofertas  →  FK: pacotes, hotels, transportes
-- ----------------------------------------------------------------------------
CREATE TABLE public.ofertas (
    id                  bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preco               numeric(10,2)   NOT NULL,
    inicio              date            NOT NULL,
    fim                 date            NOT NULL,
    disponibilidade     integer         NOT NULL,
    status              varchar(255)    NOT NULL,
    is_available        boolean         NOT NULL  DEFAULT true,
    pacote_id           bigint          NOT NULL,
    hotel_id            bigint          NOT NULL,
    transporte_id       bigint          NOT NULL,
    created_at          timestamp(0),
    updated_at          timestamp(0),

    CONSTRAINT ofertas_pacote_id_foreign
        FOREIGN KEY (pacote_id) REFERENCES public.pacotes (id) ON DELETE CASCADE,

    CONSTRAINT ofertas_hotel_id_foreign
        FOREIGN KEY (hotel_id) REFERENCES public.hotels (id) ON DELETE CASCADE,

    CONSTRAINT ofertas_transporte_id_foreign
        FOREIGN KEY (transporte_id) REFERENCES public.transportes (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- compras  →  FK: users, ofertas
-- ----------------------------------------------------------------------------
CREATE TABLE public.compras (
    id                      uuid            PRIMARY KEY,
    data_compra             timestamp(0)    NOT NULL,
    status                  varchar(255)    NOT NULL,
    metodo                  varchar(255)    NOT NULL,
    processador_pagamento   varchar(255)    NOT NULL,
    parcelas                integer         NOT NULL,
    valor_final             numeric(10,2)   NOT NULL,
    user_id                 uuid            NOT NULL,
    oferta_id               bigint          NOT NULL,
    created_at              timestamp(0),
    updated_at              timestamp(0),

    CONSTRAINT compras_user_id_foreign
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,

    CONSTRAINT compras_oferta_id_foreign
        FOREIGN KEY (oferta_id) REFERENCES public.ofertas (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- avaliacaos  →  FK: users, pacotes
-- ----------------------------------------------------------------------------
CREATE TABLE public.avaliacaos (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota            integer         NOT NULL,
    comentario      text,
    data            timestamp(0)    NOT NULL,
    user_id         uuid            NOT NULL,
    pacote_id       bigint          NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT avaliacaos_user_id_foreign
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,

    CONSTRAINT avaliacaos_pacote_id_foreign
        FOREIGN KEY (pacote_id) REFERENCES public.pacotes (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- pacote_tag (pivot)  →  FK: pacotes, tags
-- ----------------------------------------------------------------------------
CREATE TABLE public.pacote_tag (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pacote_id       bigint          NOT NULL,
    tag_id          bigint          NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT pacote_tag_pacote_id_foreign
        FOREIGN KEY (pacote_id) REFERENCES public.pacotes (id) ON DELETE CASCADE,

    CONSTRAINT pacote_tag_tag_id_foreign
        FOREIGN KEY (tag_id) REFERENCES public.tags (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- role_permissions (pivot)  →  FK: roles, permissions
-- ----------------------------------------------------------------------------
CREATE TABLE public.role_permissions (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         bigint          NOT NULL,
    permission_id   bigint          NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT role_permissions_role_id_foreign
        FOREIGN KEY (role_id) REFERENCES public.roles (id) ON DELETE CASCADE,

    CONSTRAINT role_permissions_permission_id_foreign
        FOREIGN KEY (permission_id) REFERENCES public.permissions (id) ON DELETE CASCADE
);


-- ----------------------------------------------------------------------------
-- user_permissions (pivot)  →  FK: users, permissions
-- ----------------------------------------------------------------------------
CREATE TABLE public.user_permissions (
    id              bigint          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         uuid            NOT NULL,
    permission_id   bigint          NOT NULL,
    created_at      timestamp(0),
    updated_at      timestamp(0),

    CONSTRAINT user_permissions_user_id_foreign
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,

    CONSTRAINT user_permissions_permission_id_foreign
        FOREIGN KEY (permission_id) REFERENCES public.permissions (id) ON DELETE CASCADE
);
